# Generated by Django 6.0.8 on 2026-09-03 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CheckoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_reference', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('stage', models.CharField(choices=[('cart', 'Cart'), ('shipping', 'Shipping Details'), ('payment', 'Payment Step'), ('review', 'Review / Confirm')], default='cart', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('abandoned', 'Abandoned'), ('recovered', 'Recovered')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('overdue', 'Overdue'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.customer')),
            ],
        ),
        migrations.CreateModel(
            name='RevenueEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('payment_failure', 'Payment Failure'), ('checkout_abandonment', 'Checkout Abandonment'), ('overdue_invoice', 'Overdue Invoice')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('detected', 'Detected'), ('diagnosed', 'Diagnosed'), ('decided', 'Decided'), ('in_progress', 'Intervention In Progress'), ('recovered', 'Recovered'), ('stopped', 'Stopped'), ('escalated', 'Escalated to Human')], default='detected', max_length=20)),
                ('source', models.CharField(choices=[('razorpay', 'Razorpay Webhook'), ('seed', 'Seeded Demo Data'), ('detector', 'Internal Detector Job')], default='seed', max_length=20)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_reason', models.CharField(blank=True, max_length=100)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checkout_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.checkoutsession')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.customer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.invoice')),
            ],
        ),
    ]
