# Generated by Django 6.0.8 on 2026-09-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='opted_out',
            field=models.BooleanField(default=False),
        ),
    ]
