# Generated by Django 6.0.8 on 2026-09-04 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_customer_opted_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenueevent',
            name='event_type',
            field=models.CharField(choices=[('payment_failure', 'Payment Failure'), ('checkout_abandonment', 'Checkout Abandonment'), ('overdue_invoice', 'Overdue Invoice'), ('payment_degradation', 'Payment Degradation (Predictive)')], max_length=30),
        ),
        migrations.CreateModel(
            name='PaymentAttemptLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('success', 'Success'), ('soft_decline', 'Soft Decline / Retry Needed'), ('hard_decline', 'Hard Decline')], max_length=20)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.customer')),
            ],
        ),
    ]
