# Generated by Django 6.0.8 on 2026-09-04 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_revenueevent_event_type_paymentattemptlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='language_preference',
            field=models.CharField(choices=[('en', 'English'), ('hi-en', 'Hinglish')], default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='revenueevent',
            name='recovered_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
