# Generated by Django 6.0.8 on 2026-09-03 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnosis', '0001_initial'),
        ('events', '0002_customer_opted_out'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_action', models.CharField(choices=[('retry_payment', 'Retry Payment'), ('send_payment_link', 'Send Fresh Payment Link'), ('whatsapp_nudge', 'WhatsApp Nudge'), ('email_reminder', 'Email Reminder'), ('sms_reminder', 'SMS Reminder'), ('promise_to_pay', 'Promise-to-Pay Request'), ('escalate_human', 'Escalate to Human Agent'), ('stop', 'Stop — No Further Action')], max_length=30)),
                ('expected_recovery_probability', models.FloatField(blank=True, null=True)),
                ('expected_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('expected_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('candidates_considered', models.JSONField(default=list)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnosis.diagnosis')),
                ('revenue_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='events.revenueevent')),
            ],
        ),
        migrations.CreateModel(
            name='InterventionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('retry_payment', 'Retry Payment'), ('send_payment_link', 'Send Fresh Payment Link'), ('whatsapp_nudge', 'WhatsApp Nudge'), ('email_reminder', 'Email Reminder'), ('sms_reminder', 'SMS Reminder'), ('promise_to_pay', 'Promise-to-Pay Request'), ('escalate_human', 'Escalate to Human Agent'), ('stop', 'Stop — No Further Action')], max_length=30)),
                ('outcome', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('revenue_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='events.revenueevent')),
            ],
        ),
        migrations.CreateModel(
            name='InterventionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_cause', models.CharField(max_length=50)),
                ('action', models.CharField(choices=[('retry_payment', 'Retry Payment'), ('send_payment_link', 'Send Fresh Payment Link'), ('whatsapp_nudge', 'WhatsApp Nudge'), ('email_reminder', 'Email Reminder'), ('sms_reminder', 'SMS Reminder'), ('promise_to_pay', 'Promise-to-Pay Request'), ('escalate_human', 'Escalate to Human Agent'), ('stop', 'Stop — No Further Action')], max_length=30)),
                ('base_recovery_probability', models.FloatField()),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'unique_together': {('root_cause', 'action')},
            },
        ),
    ]
