# Generated by Django 6.0.8 on 2026-09-03 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_customer_opted_out'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_cause', models.CharField(max_length=50)),
                ('explanation', models.CharField(max_length=255)),
                ('confidence', models.FloatField(default=1.0)),
                ('diagnosed_at', models.DateTimeField(auto_now_add=True)),
                ('revenue_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='events.revenueevent')),
            ],
        ),
    ]
