# Generated by Django 6.0.8 on 2026-09-04 09:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0004_customer_language_preference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('payment_link_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revenue_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_link', to='events.revenueevent')),
            ],
        ),
    ]
