# Generated by Django 6.0.8 on 2026-09-03 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_customer_opted_out'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('diagnosed', 'Diagnosed'), ('decided', 'Decided'), ('action_attempted', 'Action Attempted'), ('outcome_recorded', 'Outcome Recorded')], max_length=30)),
                ('detail', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revenue_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trail', to='events.revenueevent')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
