# Generated by Django 6.0.8 on 2026-09-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='stage',
            field=models.CharField(choices=[('diagnosed', 'Diagnosed'), ('decided', 'Decided'), ('action_attempted', 'Action Attempted'), ('outcome_recorded', 'Outcome Recorded'), ('customer_action', 'Customer Action')], max_length=30),
        ),
    ]
